authors:
  nedevski:
    name: Nikola Nedevski # Author name
    description: asdf # Author description
    avatar: https://avatars.githubusercontent.com/u/7324633 # Author avatar
    slug: nedevski # Author profile slug
    url: https://github.com/nedevski # Author website URL
